# Generate event-aligned h5 datasets

New-pipeline version of `OLDPIPELINEFILES/generate_h5_dataset.ipynb`: load a session, choose units by their quality metrics, align spikes to task events, and save one h5 file per event.

To process many sessions without the notebook, list them in a config file and run `python scripts/generate_h5_dataset.py config.toml` (see `scripts/example_config.toml`).

In [1]:
from pathlib import Path

import numpy as np

from ephys_behavior_formatting import AlignedSpikes, NeuropixelsExperiment, PlexonExperiment, UnitCriteria

/opt/miniconda3/envs/ephys-fmt/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Neuropixels sessions

## Load the session

`kilosort_dir` is the Kilosort output folder. The raw `.ap.bin`/`.ap.meta` files are found there or in its parent folder (pass `raw_dir=` otherwise).

In [2]:
monkey_id = "B"
session_date = "20250325"

ssd = Path("/media/mateoumaguing/Extreme SSD")
kilosort_dir = ssd / "example_npix_session/BILBO_CHKDLAY_DLPFC_03252025_g0/BILBO_CHKDLAY_DLPFC_03252025_g0_imec0/kilosort4"
events_path = ssd / f"CFD_DLPFC/BilboEvents/{session_date}/CFDeventStruct.mat"

experiment = NeuropixelsExperiment(
    kilosort_dir,
    events_path,
    monkey_id=monkey_id,
    session_date=session_date,
    roi="DLPFC",
    task_type="CHKDLAY",
)

## Load units

Reads every unit's spike times and a sample of its waveforms (used for SNR and amplitude cutoff). Restrict with `unit_ids=` or `quality_labels=("good",)`.

In [3]:
experiment.load_units(n_jobs=8);

Loading units: 100%|██████████| 392/392 [03:15<00:00,  2.01it/s]

Loaded 392 of 392 units.

## Trial parameters

In [4]:
trials = experiment.trial_params_frame()
print(f"{len(trials)} trials")
trials.head(10)

645 trials

,trial_outcomes,trial_RTs,trial_action_choices,trial_cues,trial_configs,trial_color_choices,trial_delay_lengths,trial_savetags,trial_unique_ids
0,incorrect,787,right,135,RG,green,601,1,63910262980
1,correct,769,right,45,RG,green,515,1,63910262988
2,correct,1042,left,90,GR,green,703,1,63910262993
3,correct,826,left,108,GR,green,567,1,63910262998
4,correct,775,right,180,GR,red,483,1,63910263002
5,correct,796,left,11,GR,green,593,1,63910263007
6,incorrect,847,left,147,GR,green,607,1,63910263011
7,incorrect,824,right,78,GR,red,539,1,63910263020
8,correct,850,right,67,RG,green,790,1,63910263028
9,correct,708,left,135,RG,red,483,1,63910263033

## Choose units by quality metrics

Every criterion left unset is ignored. `include_ids` / `exclude_ids` override the criteria for hand-picked units.

In [5]:
metrics = experiment.unit_metrics()
metrics.describe()

/home/mateoumaguing/Documents/MiscData/ephys-behavior-formatting/src/ephys_behavior_formatting/units.py:156: UserWarning: Unit 376: amplitude pdf has no unique minimum; amplitude_cutoff may be unreliable with this few waveforms.
  "amplitude_cutoff": self.amplitude_cutoff(),

,num_spikes,firing_rate,isi_mean,isi_std,isi_violations_ratio,isi_violations_count,presence_ratio,amplitude_cutoff,snr
count,392.000000,392.000000,391.000000,391.000000,392.000000,392.000000,391.000000,392.000000,391.000000
mean,11132.362245,2.819038,7.304244,10.451450,1.533412,49.456633,0.971204,0.048049,2.047653
std,13661.857156,3.457475,51.165411,63.341956,12.956431,117.619931,0.114051,0.079518,1.302878
min,1.000000,0.000000,0.058730,0.079820,0.000000,0.000000,0.066667,0.000000,0.595182
25%,1279.500000,0.324541,0.223005,0.365324,0.000000,0.000000,1.000000,0.010795,1.317530
50%,4908.000000,1.242813,0.799354,1.356263,0.136697,2.500000,1.000000,0.022129,1.647051
75%,17666.500000,4.473522,3.073476,4.287258,0.347106,33.250000,1.000000,0.052900,2.244729
max,67278.000000,17.027290,913.490302,1058.868932,219.831895,878.000000,1.000000,0.500000,10.216527

In [6]:
criteria = UnitCriteria(
    quality_labels=("good", "mua"),
    min_firing_rate=1.0,          # Hz
    max_isi_violations_ratio=1,
    min_presence_ratio=0.9,
    # min_snr=3.0,
    # max_amplitude_cutoff=0.1,
    # include_ids=[...],
    # exclude_ids=[...],
)
selected = experiment.select_units(criteria)
print(f"{len(selected)} of {len(experiment.units)} units pass")

204 of 392 units pass

## Align spikes and save

Each file holds `spike_counts` with shape (trials, units, time bins), plus trial parameters, unit ids, unit metrics and the criteria used.

In [7]:
savepath = Path("/home/mateoumaguing/Documents/MiscData/CFD_data_h5")
overwrite = True  # replace files from earlier runs of this notebook

alignments = [
    {"event_name": "CheckerboardDrawnTime", "pre_time": 0.400, "post_time": 2.000},
    {"event_name": "TargetsDrawnTime", "pre_time": 1.800, "post_time": 1.000},
]

for alignment in alignments:
    aligned = experiment.align_spikes(**alignment, bin_size=0.001, criteria=criteria)
    path = aligned.save(savepath, overwrite=overwrite)
    print(f"{aligned.spike_counts.shape} -> {path}")

(645, 204, 2400) -> /home/mateoumaguing/Documents/MiscData/CFD_data_h5/B_CHKDLAY_DLPFC_20250325_CheckerboardAligned.h5
(645, 204, 2800) -> /home/mateoumaguing/Documents/MiscData/CFD_data_h5/B_CHKDLAY_DLPFC_20250325_TargetsAligned.h5

## Load a saved file

In [8]:
loaded = AlignedSpikes.load(savepath / f"{monkey_id}_CHKDLAY_DLPFC_{session_date}_CheckerboardAligned.h5")

print(loaded.metadata)
print(loaded.spike_counts.shape)  # (trials, units, time bins)
loaded.trial_params_frame().head()

{'monkey_id': 'B', 'session_date': '20250325', 'roi': 'DLPFC', 'task_type': 'CHKDLAY', 'probe_type': 'Neuropixels'}
(645, 204, 2400)

,trial_RTs,trial_action_choices,trial_color_choices,trial_configs,trial_cues,trial_delay_lengths,trial_outcomes,trial_savetags,trial_unique_ids
trial_index,,,,,,,,,
0,787,right,green,RG,135,601,incorrect,1,63910262980
1,769,right,green,RG,45,515,correct,1,63910262988
2,1042,left,green,GR,90,703,correct,1,63910262993
3,826,left,green,GR,108,567,correct,1,63910262998
4,775,right,red,GR,180,483,correct,1,63910263002

In [9]:
# e.g. correct trials only, from -400 to 900 ms
window = loaded.select_trials(loaded.trial_params["trial_outcomes"] == "correct").time_window(-0.400, 0.900)
window.spike_counts.shape

(504, 204, 1300)

# Plexon sessions

Same steps for a Plexon session. `PlexonExperiment` starts from the session's `allTrials` file (assembled from the raw per-trial `.dat` files by `PlexonSessionProcessor`, see the end of this notebook).

Plexon files have no hand-movement event, so reaction times come from the session's `CFDeventStruct.mat` (`events_path`), matched to the Plexon trials by unique id. Without it, `trial_RTs` is NaN.

## Load the session

In [ ]:
plexon_monkey_id = "T"
plexon_session_date = "20220309"

plexon = PlexonExperiment(
    ssd / f"CFD_plexon_data/TiberiusCHKDLAY{plexon_session_date}.mat",
    monkey_id=plexon_monkey_id,
    session_date=plexon_session_date,
    roi="DLPFC",
    task_type="CHKDLAY",
    events_path=ssd / f"CFD_DLPFC/TiberiusEvents/{plexon_session_date}/CFDeventStruct.mat",
    # valid_savetags=[1, 2],     # keep only these recording blocks
    # include_unsorted=True,     # also treat each channel's unsorted spikes (unit 0) as a unit
)

## Load units

Unit ids are `channel * 100 + unit` (e.g. 1302 = channel 13, unit 2).

In [ ]:
plexon.load_units();

## Trial parameters

In [ ]:
plexon_trials = plexon.trial_params_frame()
print(f"{len(plexon_trials)} trials, {plexon_trials['trial_RTs'].isna().sum()} without an RT")
plexon_trials.head(10)

## Choose units by quality metrics

Two metrics behave differently for Plexon data:
- **ISI violations** are not meaningful: spike times are xPC packet timestamps with ~1 ms resolution.
- **Amplitude cutoff** is usually at its 0.5 cap: Plexon only stores threshold-crossing snippets, so the low-amplitude side of the distribution is missing.

In [ ]:
plexon.unit_metrics().describe()

In [ ]:
plexon_criteria = UnitCriteria(
    min_firing_rate=1.0,  # Hz
    min_presence_ratio=0.9,
    # min_snr=2.0,
    # include_ids=[...],
    # exclude_ids=[...],
)
plexon_selected = plexon.select_units(plexon_criteria)
print(f"{len(plexon_selected)} of {len(plexon.units)} units pass")

## Align spikes and save

In [ ]:
for alignment in alignments:
    aligned = plexon.align_spikes(**alignment, bin_size=0.001, criteria=plexon_criteria)
    path = aligned.save(savepath, overwrite=overwrite)
    print(f"{aligned.spike_counts.shape} -> {path}")

## Load a saved file

In [ ]:
plexon_loaded = AlignedSpikes.load(
    savepath / f"{plexon_monkey_id}_CHKDLAY_DLPFC_{plexon_session_date}_TargetsAligned.h5"
)
print(plexon_loaded.metadata)
print(plexon_loaded.spike_counts.shape)  # (trials, units, time bins)
plexon_loaded.trial_params_frame().head()

## Building `allTrials` from raw `.dat` files

Only needed for sessions that haven't been processed yet. Requires MATLAB and the MATLAB Engine for Python (`scripts/install_matlab_engine.sh`).

In [2]:
from ephys_behavior_formatting.plexon import PlexonSessionProcessor

plexon_mat_path = Path("/Users/mateouma/Documents/PhDing/ChandLab/miscdata/plexon_processed")
processor = PlexonSessionProcessor("/Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426", task_type="CHKDLAY")
processor.process(include_spikes=True, include_lfp=False)
processor.save(plexon_mat_path, monkey_id="T", date="20230426")

Reading trials:   0%|          | 1/360 [00:04<28:46,  4.81s/trial]

Error processing Tiberius-CHKDLAY-EVTS-63849876868-00000015.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849876868-00000015.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876877-00000017.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849876877-00000017.dat

Reading trials:   2%|▏         | 6/360 [00:05<03:26,  1.71trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849876885-00000019.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849876885-00000019.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876889-00000020.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849876889-00000020.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876904-00000023.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849876904-00000023.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876907-00000024.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849876907-00000024.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876929-00000029.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849876929-00000029.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876936-00000031.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849876936-00000031.dat

Reading trials:   6%|▌         | 20/360 [00:05<00:36,  9.41trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849876972-00000040.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849876972-00000040.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876987-00000043.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849876987-00000043.dat
Error processing Tiberius-CHKDLAY-EVTS-63849876992-00000044.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849876992-00000044.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877007-00000048.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877007-00000048.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877012-00000049.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877012-00000049.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877015-00000050.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877015-00000050.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877023-00000052.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877023-00000052.dat

Reading trials:   7%|▋         | 26/360 [00:06<00:23, 14.24trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877027-00000053.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877027-00000053.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877046-00000058.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877046-00000058.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877058-00000061.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877058-00000061.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877063-00000062.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877063-00000062.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877069-00000063.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877069-00000063.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877094-00000068.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877094-00000068.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877098-00000069.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877098-00000069.dat

Reading trials:  11%|█         | 38/360 [00:06<00:13, 24.69trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877109-00000072.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877109-00000072.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877113-00000073.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877113-00000073.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877122-00000075.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877122-00000075.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877131-00000077.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877131-00000077.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877137-00000078.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877137-00000078.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877143-00000079.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877143-00000079.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877147-00000080.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877147-00000080.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877167-00000084.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877167-00000084.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877174-00000086.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877174-00000086.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877178-00000087.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877178-00000087.dat

Reading trials:  14%|█▍        | 50/360 [00:06<00:08, 34.89trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877187-00000089.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877187-00000089.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877191-00000090.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877191-00000090.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877198-00000092.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877198-00000092.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877208-00000094.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877208-00000094.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877215-00000096.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877215-00000096.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877219-00000097.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877219-00000097.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877227-00000099.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877227-00000099.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877244-00000103.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877244-00000103.dat

Reading trials:  15%|█▌        | 55/360 [00:06<00:09, 33.89trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877269-00000109.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877269-00000109.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877281-00000112.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877281-00000112.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877299-00000116.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877299-00000116.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877303-00000117.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877303-00000117.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877319-00000120.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877319-00000120.dat

Reading trials:  18%|█▊        | 65/360 [00:06<00:08, 34.06trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877325-00000121.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877325-00000121.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877363-00000130.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877363-00000130.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877370-00000132.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877370-00000132.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877374-00000133.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877374-00000133.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877383-00000135.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877383-00000135.dat

Reading trials:  22%|██▏       | 78/360 [00:07<00:06, 46.47trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877386-00000136.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877386-00000136.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877394-00000138.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877394-00000138.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877398-00000139.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877398-00000139.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877402-00000140.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877402-00000140.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877409-00000142.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877409-00000142.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877419-00000144.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877419-00000144.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877431-00000147.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877431-00000147.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877441-00000149.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877441-00000149.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877445-00000150.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877445-00000150.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877453-00000152.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877453-00000152.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877465-00000154.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877465-00000154.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877473-00000156.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877473-00000156.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877477-00000157.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877477-00000157.dat

Reading trials:  25%|██▍       | 89/360 [00:07<00:06, 42.05trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877490-00000160.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877490-00000160.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877497-00000161.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877497-00000161.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877500-00000162.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877500-00000162.dat

Reading trials:  29%|██▊       | 103/360 [00:07<00:04, 52.11trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877534-00000170.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877534-00000170.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877538-00000171.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877538-00000171.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877547-00000173.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877547-00000173.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877554-00000174.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877554-00000174.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877560-00000175.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877560-00000175.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877564-00000176.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877564-00000176.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877570-00000177.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877570-00000177.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877574-00000178.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877574-00000178.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877581-00000180.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877581-00000180.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877585-00000181.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877585-00000181.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877589-00000182.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877589-00000182.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877593-00000183.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877593-00000183.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877606-00000186.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877606-00000186.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877616-00000188.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877616-00000188.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877620-00000189.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877620-00000189.dat

Reading trials:  32%|███▏      | 115/360 [00:07<00:04, 51.24trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877640-00000193.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877640-00000193.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877646-00000194.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877646-00000194.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877650-00000195.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877650-00000195.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877654-00000196.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877654-00000196.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877662-00000198.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877662-00000198.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877667-00000199.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877667-00000199.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877671-00000200.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877671-00000200.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877677-00000201.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877677-00000201.dat

Reading trials:  36%|███▌      | 128/360 [00:08<00:04, 51.35trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877693-00000205.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877693-00000205.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877697-00000206.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877697-00000206.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877700-00000207.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877700-00000207.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877714-00000210.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877714-00000210.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877718-00000211.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877718-00000211.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877721-00000212.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877721-00000212.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877744-00000217.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877744-00000217.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877756-00000220.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877756-00000220.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877783-00000226.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877783-00000226.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877791-00000228.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877791-00000228.dat

Reading trials:  39%|███▉      | 140/360 [00:08<00:04, 50.08trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877795-00000229.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877795-00000229.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877811-00000232.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877811-00000232.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877815-00000233.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877815-00000233.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877819-00000234.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877819-00000234.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877825-00000235.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877825-00000235.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877829-00000236.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877829-00000236.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877841-00000239.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877841-00000239.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877848-00000241.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877848-00000241.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877852-00000242.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877852-00000242.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877860-00000244.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877860-00000244.dat

Reading trials:  41%|████▏     | 149/360 [00:08<00:03, 57.00trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877866-00000245.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877866-00000245.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877870-00000246.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877870-00000246.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877875-00000247.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877875-00000247.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877880-00000248.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877880-00000248.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877898-00000252.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877898-00000252.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877902-00000253.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877902-00000253.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877918-00000257.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877918-00000257.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877923-00000258.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877923-00000258.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877926-00000259.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877926-00000259.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877930-00000260.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877930-00000260.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877934-00000261.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877934-00000261.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877939-00000262.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877939-00000262.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877948-00000264.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877948-00000264.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877952-00000265.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877952-00000265.dat

Reading trials:  46%|████▌     | 166/360 [00:08<00:03, 61.20trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849877956-00000266.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877956-00000266.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877961-00000267.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877961-00000267.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877970-00000269.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877970-00000269.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877983-00000272.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849877983-00000272.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877986-00000273.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877986-00000273.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877990-00000274.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877990-00000274.dat
Error processing Tiberius-CHKDLAY-EVTS-63849877994-00000275.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849877994-00000275.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878001-00000277.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878001-00000277.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878013-00000280.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878013-00000280.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878017-00000281.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878017-00000281.dat

Reading trials:  50%|█████     | 180/360 [00:09<00:02, 60.96trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878038-00000286.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878038-00000286.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878044-00000287.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878044-00000287.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878051-00000288.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878051-00000288.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878068-00000292.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878068-00000292.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878072-00000293.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878072-00000293.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878079-00000294.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878079-00000294.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878088-00000296.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878088-00000296.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878092-00000297.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878092-00000297.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878101-00000299.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878101-00000299.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878123-00000304.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878123-00000304.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878129-00000305.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878129-00000305.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878135-00000306.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878135-00000306.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878148-00000309.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878148-00000309.dat

Reading trials:  54%|█████▍    | 195/360 [00:09<00:02, 58.67trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878152-00000310.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878152-00000310.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878158-00000311.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878158-00000311.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878162-00000312.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878162-00000312.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878168-00000313.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878168-00000313.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878182-00000316.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878182-00000316.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878186-00000317.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878186-00000317.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878190-00000318.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878190-00000318.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878194-00000319.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878194-00000319.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878200-00000320.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878200-00000320.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878207-00000322.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878207-00000322.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878220-00000325.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878220-00000325.dat

Reading trials:  56%|█████▋    | 203/360 [00:09<00:02, 60.52trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878224-00000326.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878224-00000326.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878229-00000327.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878229-00000327.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878233-00000328.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878233-00000328.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878239-00000329.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878239-00000329.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878248-00000331.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878248-00000331.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878253-00000332.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878253-00000332.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878261-00000334.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878261-00000334.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878269-00000336.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878269-00000336.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878277-00000338.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878277-00000338.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878280-00000339.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878280-00000339.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878288-00000341.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878288-00000341.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878296-00000343.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878296-00000343.dat

Reading trials:  60%|██████    | 217/360 [00:09<00:02, 54.94trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878308-00000346.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878308-00000346.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878334-00000352.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878334-00000352.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878337-00000353.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878337-00000353.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878342-00000354.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878342-00000354.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878346-00000355.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878346-00000355.dat

Reading trials:  62%|██████▏   | 223/360 [00:09<00:02, 51.73trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878358-00000358.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878358-00000358.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878376-00000362.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878376-00000362.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878380-00000363.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878380-00000363.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878386-00000364.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878386-00000364.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878394-00000366.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878394-00000366.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878419-00000371.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878419-00000371.dat

Reading trials:  65%|██████▌   | 235/360 [00:10<00:02, 49.94trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878443-00000376.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878443-00000376.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878451-00000378.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878451-00000378.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878455-00000379.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878455-00000379.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878458-00000380.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878458-00000380.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878466-00000382.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878466-00000382.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878480-00000385.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878480-00000385.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878488-00000387.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878488-00000387.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878492-00000388.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878492-00000388.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878510-00000392.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878510-00000392.dat

Reading trials:  67%|██████▋   | 241/360 [00:10<00:02, 43.13trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878517-00000394.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878517-00000394.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878523-00000395.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878523-00000395.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878528-00000396.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878528-00000396.dat

Reading trials:  70%|██████▉   | 251/360 [00:10<00:02, 38.65trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878557-00000403.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878557-00000403.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878561-00000404.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878561-00000404.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878571-00000406.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878571-00000406.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878576-00000407.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878576-00000407.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878595-00000412.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878595-00000412.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878603-00000414.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878603-00000414.dat

Reading trials:  72%|███████▎  | 261/360 [00:10<00:02, 36.56trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878629-00000420.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878629-00000420.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878637-00000422.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878637-00000422.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878647-00000424.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878647-00000424.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878659-00000427.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878659-00000427.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878675-00000431.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878675-00000431.dat

Reading trials:  74%|███████▍  | 268/360 [00:10<00:02, 41.72trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878679-00000432.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878679-00000432.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878684-00000433.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878684-00000433.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878688-00000434.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878688-00000434.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878692-00000435.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878692-00000435.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878704-00000437.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878704-00000437.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878716-00000440.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878716-00000440.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878731-00000444.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878731-00000444.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878740-00000446.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878740-00000446.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878746-00000447.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878746-00000447.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878750-00000448.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878750-00000448.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878755-00000449.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878755-00000449.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878765-00000451.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878765-00000451.dat

Reading trials:  80%|███████▉  | 287/360 [00:11<00:01, 49.11trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878794-00000458.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878794-00000458.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878803-00000460.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878803-00000460.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878807-00000461.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878807-00000461.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878811-00000462.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878811-00000462.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878821-00000464.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878821-00000464.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878833-00000467.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878833-00000467.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878841-00000469.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878841-00000469.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878847-00000470.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878847-00000470.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878853-00000471.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878853-00000471.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878866-00000474.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878866-00000474.dat

Reading trials:  81%|████████▏ | 293/360 [00:11<00:01, 48.68trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878880-00000477.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878880-00000477.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878884-00000478.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878884-00000478.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878891-00000480.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878891-00000480.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878901-00000482.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878901-00000482.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878918-00000485.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878918-00000485.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878925-00000487.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878925-00000487.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878939-00000490.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878939-00000490.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878958-00000495.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878958-00000495.dat

Reading trials:  85%|████████▌ | 306/360 [00:11<00:01, 53.53trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849878966-00000497.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878966-00000497.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878977-00000500.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878977-00000500.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878982-00000501.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878982-00000501.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878985-00000502.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849878985-00000502.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878994-00000504.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878994-00000504.dat
Error processing Tiberius-CHKDLAY-EVTS-63849878998-00000505.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849878998-00000505.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879002-00000506.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879002-00000506.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879018-00000509.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879018-00000509.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879022-00000510.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879022-00000510.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879026-00000511.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879026-00000511.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879030-00000512.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879030-00000512.dat

Reading trials:  88%|████████▊ | 318/360 [00:11<00:00, 47.88trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849879038-00000514.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879038-00000514.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879046-00000516.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879046-00000516.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879050-00000517.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879050-00000517.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879054-00000518.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879054-00000518.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879057-00000519.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879057-00000519.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879061-00000520.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879061-00000520.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879084-00000525.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879084-00000525.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879089-00000526.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879089-00000526.dat

Reading trials:  92%|█████████▎| 333/360 [00:12<00:00, 57.15trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849879099-00000528.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879099-00000528.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879108-00000530.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879108-00000530.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879112-00000531.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879112-00000531.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879119-00000533.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879119-00000533.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879127-00000535.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879127-00000535.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879142-00000539.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879142-00000539.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879156-00000542.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879156-00000542.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879163-00000544.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879163-00000544.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879167-00000545.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879167-00000545.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879173-00000546.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879173-00000546.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879177-00000547.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879177-00000547.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879185-00000549.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879185-00000549.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879195-00000551.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879195-00000551.dat

Reading trials:  94%|█████████▍| 339/360 [00:12<00:00, 52.44trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849879203-00000553.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879203-00000553.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879206-00000554.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879206-00000554.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879211-00000555.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879211-00000555.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879222-00000558.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879222-00000558.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879251-00000564.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879251-00000564.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879263-00000566.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879263-00000566.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879267-00000567.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879267-00000567.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879275-00000569.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879275-00000569.dat

Reading trials:  98%|█████████▊| 352/360 [00:12<00:00, 54.74trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849879280-00000570.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879280-00000570.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879290-00000572.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879290-00000572.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879298-00000574.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879298-00000574.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879317-00000579.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879317-00000579.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879324-00000580.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879324-00000580.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879328-00000581.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-CONT-63849879328-00000581.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879331-00000582.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879331-00000582.dat

Reading trials: 100%|██████████| 360/360 [00:12<00:00, 28.35trial/s]

Error processing Tiberius-CHKDLAY-EVTS-63849879364-00000588.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879364-00000588.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879389-00000593.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879389-00000593.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879393-00000594.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879393-00000594.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879400-00000596.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879400-00000596.dat
Error processing Tiberius-CHKDLAY-EVTS-63849879409-00000598.dat: /Users/mateouma/Documents/PhDing/ChandLab/miscdata/20230426/Tiberius-CHKDLAY-BEHV-63849879409-00000598.dat
        total_trials: 75
         num_correct: 61
       num_incorrect: 14
            accuracy: 0.813
       single_trials: 0
       double_trials: 75
  broke_center_holds: 0
    broke_center_pct: 0.000
Saved 75 trials to /Users/mateouma/Documents/PhDing/ChandLab/miscdata/plexon_processed/TCHKDLAY20230426.mat

PosixPath('/Users/mateouma/Documents/PhDing/ChandLab/miscdata/plexon_processed/TCHKDLAY20230426.mat')